import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Button } from "~/components/ui/Button";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const router = useRouter();
  const { mutate } = api.rooms.create.useMutation({
    onSuccess: async (data) => {
      await router.push(`/room/${data.id}`);
    },
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div >
          <Button
            onClick={() => mutate()}
            className="text-3xl"
          >
            Create room
          </Button>
        </div>
      </main>
    </>
  );
};

export default Home;
