import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { PageLayout } from "~/components/layot";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [input, setInput] = useState("");
  const [disabled, setDisabled] = useState(true);

  const router = useRouter();

  const createRoom = api.rooms.create.useMutation({
    onSuccess: async (data) => {
      await router.push(`/room/${data.id}`);
    },
  });

  useEffect(() => {
    input.trim().length === 0 ? setDisabled(true) : setDisabled(false);
  }, [input]);

  const joinRoomById = api.rooms.getRoomById.useQuery(
    { roomId: input },
    {
      onSuccess: (data) => {
        void router.push(`/room/${data.id}`);
      },
      onError: () => {
        console.log("Smt bad");
      },
      enabled: false,
    }
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <div className="hero h-full">
          <div className="hero-content text-center">
            <div className="max-w-md">
              <h1 className="text-5xl font-bold">Hello there</h1>
              <p className="py-10">
                Provident cupiditate voluptatem et in. Quaerat fugiat ut
                assumenda excepturi exercitationem quasi. In deleniti eaque aut
                repudiandae et a id nisi.
              </p>
              <button
                className="btn-primary btn-block btn"
                onClick={() => createRoom.mutate()}
              >
                Create room
              </button>
              <div className="divider">OR</div>
              <div className="form-control">
                <div className="input-group">
                  <input
                    type="text"
                    placeholder="Paste room Id"
                    className="input-bordered input w-full"
                    onChange={({ target }) => setInput(target.value)}
                    value={input}
                  />
                  <button
                    className="btn-primary btn"
                    disabled={disabled}
                    onClick={() => {
                      void joinRoomById.refetch();
                    }}
                  >
                    Join Room
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </PageLayout>
    </>
  );
};

export default Home;
